apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component-pac-dama
  namespace: test-pac
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: build-suite-test-application-ytbx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component-pac-dama
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component-pac-dama-
      labels:
        build.appstudio.openshift.io/application: build-suite-test-application-ytbx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component-pac-dama
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test-pac
    spec:
      params:
      - name: git-url
        value: https://github.com/psturc-org/devfile-sample-hello-world
      - name: output-image
        value: quay.io/psturc/test-images:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test-component-pac-dama/$(tt.params.git-revision)
    status: {}
status: {}
